hotels/config/routes.rb
Rails.application.routes.draw do
  resources :hotels do
    collection do
      get 'search'
    end
  end

  root 'hotels#index'
end

hotels/app/models/accomodation_type.rb
class AccomodationType < ActiveRestClient::Base
  base_url Rails.application.config.api_server_url

  get :all, "/accomodation_types"

end

hotels/app/models/hotel.rb
class Hotel < ActiveRestClient::Base
  include ActiveAttr::BasicModel
  base_url Rails.application.config.api_server_url

  get :all, "/hotels"
  get :find, "/hotels/:id"
  put :save, "/hotels/:id"
  post :create, "/hotels"
  delete :destroy, "/hotels/:id"
end

hotels/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

hotels/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  def show
  end

  # GET /hotels/new
  def new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  def create
    has_error = false
    begin
      @hotel = Hotel.create(:hotel => hotel_params)
    rescue Exception => exception
      has_error = true
      json_errors = exception.result.to_json
      @errors = JSON.parse(json_errors)

    end

    unless has_error
      redirect_to hotel_path(@hotel.id), notice: 'Hotel was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /hotels/1
  def update
    has_error = false
    begin
      @hotel.hotel = hotel_params
      @hotel = @hotel.save
    rescue Exception => exception
      has_error = true
      json_errors = exception.result.to_json
      @errors = JSON.parse(json_errors)

    end

    unless has_error
      redirect_to hotel_path(@hotel.id), notice: 'Hotel was successfully updated.'
    else
      render :edit
    end

  end

  # DELETE /hotels/1
  def destroy
    @hotel.destroy
    redirect_to hotels_url, notice: 'Hotel was successfully deleted.'
  end

  def search
    search_response = HTTParty.get(Rails.application.config.api_server_url+"/hotels/search.json?query="+params[:query])
    response = []
    if search_response.length
      search_response.each do |hotel|
        response << { value: hotel["name"]+"<br/>"+hotel["address"], data: hotel["id"]  }
      end
    end
    render json: {:suggestions => response}
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def hotel_params
      params.permit(:name, :address, :star_rating, :accomodation_type_id)
    end
end

hotels/app/helpers/application_helper.rb
module ApplicationHelper
end

hotels/app/helpers/hotels_helper.rb
module HotelsHelper
end

hotels/app/views/hotels/_create.html.erb
<%= form_tag(hotels_path,:method => :post) do %>

    <% if !@errors.nil? && @errors.count %>
        <div id="error_explanation">
          <h2><%= pluralize(@errors.count, "error") %> prohibited this hotel from being saved:</h2>

          <ul>
            <% @errors.each do |field, error_messages| %>
                <% error_messages.each do |error_message|%>
                    <li><%= field %>: <%=error_message%></li>
                <%end%>
            <% end %>
          </ul>
        </div>
    <% end %>

  <div class="field">
    <%= label_tag :name %><br>
    <%= text_field_tag :name %>
  </div>
  <div class="field">
    <%= label_tag :address %><br>
    <%= text_field_tag :address %>
  </div>
  <div class="field">
    <%= label_tag :star_rating %><br>
    <%=select_tag :star_rating, options_for_select((1..5).to_a), :class=> "star-rating"%>
  </div>


    <div class="field">
    <%= label_tag :accomodation_type_id, "Accomodation Type" %><br>
    <%=select_tag :accomodation_type_id, options_from_collection_for_select(AccomodationType.all, "id", "name")%>
    </div>
  <div class="actions right">
    <%= submit_tag "Add", :class =>"expanded large button success float-right"  %>
  </div>
<% end %>

hotels/app/views/hotels/_update.html.erb
<%= form_tag(hotel_path(@hotel.id),:method => :put) do %>

    <% if !@errors.nil? && @errors.count %>
        <div id="error_explanation">
          <h2><%= pluralize(@errors.count, "error") %> prohibited this hotel from being saved:</h2>

          <ul>
            <% @errors.each do |field, error_messages| %>
                <% error_messages.each do |error_message|%>
                    <li><%= field %>: <%=error_message%></li>
                <%end%>
            <% end %>
          </ul>
        </div>
    <% end %>

  <div class="field">
    <%= label_tag :name %><br>
    <%= text_field_tag :name, @hotel.name %>
  </div>
  <div class="field">
    <%= label_tag :address %><br>
    <%= text_field_tag :address, @hotel.address %>
  </div>
  <div class="field">
    <%= label_tag :star_rating %><br>
    <%=select_tag :star_rating, options_for_select((1..5).to_a, @hotel.star_rating.to_i), :class=> "star-rating"%>
  </div>


    <div class="field">
    <%= label_tag :accomodation_type_id, "Accomodation Type" %><br>
    <%=select_tag :accomodation_type_id, options_from_collection_for_select(AccomodationType.all, "id", "name", @hotel.accomodation_type_id)%>
    </div>
  <div class="actions right">
    <%= submit_tag "Update", :class =>"expanded large button success float-right"  %>
  </div>
<% end %>

hotels/app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'update' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

hotels/app/views/hotels/index.html.erb
<h1>Listing Hotels</h1>
<div class="row">
  <div class="small-offset-3 small-6 columns">
    <input type="text" name="search" id="autocomplete" placeholder="Search for a hotel by name or address"/>
  </div>
</div>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Star rating</th>
      <th>Accomodation type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= hotel.address %></td>
        <td><%=select_tag :star_rating, options_for_select((1..5).to_a, hotel.star_rating.to_i), :class=> "star-rating-disabled"%></td>
        <td><%= hotel.accomodation_type_name %></td>
        <td><%= link_to 'Show', hotel_path(hotel.id) %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel.id) %></td>
        <td><%= link_to 'Delete', hotel_path(hotel.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path, :class => "button large float-right" %>

hotels/app/views/hotels/new.html.erb
<h1>New Hotel</h1>

<%= render 'create' %>

<%= link_to 'Back', hotels_path %>

hotels/app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hotel.address %>
</p>

<p>
  <strong>Star rating:</strong>
  <%=select_tag :star_rating, options_for_select((1..5).to_a, @hotel.star_rating.to_i), :class=> "star-rating-disabled"%>
</p>

<p>
  <strong>Accomodation type:</strong>
  <%= @hotel.accomodation_type_name %>
</p>

<%= link_to 'Edit', edit_hotel_path(@hotel.id) %> |
<%= link_to 'Back', hotels_path %>

hotels/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "Hotels" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="top-bar">
  <div class="top-bar-title">
    <span data-responsive-toggle="responsive-menu" data-hide-for="medium">
      <button class="menu-icon dark" type="button" data-toggle></button>
    </span>
    <a href="<%=root_path%>"><strong>Hotels</strong></a>
  </div>

</div>

<%= display_flash_messages %>
<div class="row">
<%= yield %>
</div>

</body>
</html>